title: Apuntes
theme: jekyll-theme-primer

exclude:
  - node_modules
  - scripts
  - code
  - "**/grafana_data"
  - "**/*.db"

defaults:
  -
    scope:
      path: "documents"
    values:
      layout: null