(extraerrecurso enano1 moria mithril)
(viajar hobbit4 bree rivendell)
(formarcomunidad hobbit4 mago1 rivendell)
(recogerobjeto hobbit4 rivendell anillo)
(viajarcomunidad hobbit4 mago1 rivendell moria)
(materializarchaleco mago1 moria)
(recogerobjeto hobbit4 moria chalecomithril)
(viajarcomunidad hobbit4 mago1 moria lothlorien)
(recogerobjeto hobbit4 lothlorien espada)
(viajarcomunidad hobbit4 mago1 lothlorien amonhen)
(viajarcomunidad hobbit4 mago1 amonhen deadmarshes)
(viajarcomunidad hobbit4 mago1 deadmarshes minasmorgul)
(viajarcomunidad hobbit4 mago1 minasmorgul orodruin)
(destruiranillo hobbit4 orodruin)
; cost = 14 (unit cost)
