(viajar enano1 tharbad bree)
(viajar enano1 bree rivendell)
(viajar hobbit1 lothlorien amonhen)
(viajar enano1 rivendell moria)
(viajar hobbit1 amonhen deadmarshes)
(viajar hobbit1 deadmarshes minasmorgul)
(viajar hobbit1 minasmorgul minastirith)
(viajar hobbit1 minastirith edoras)
(viajar hobbit1 edoras helmsdeep)
(viajar hobbit1 helmsdeep tharbad)
(viajar hobbit1 tharbad hobbiton)
(extraerrecurso hobbit1 hobbiton alimento)
(extraerrecurso enano1 moria mithril)
; cost = 23 (general cost)
