(extraerrecurso enano1 moria mithril)
(viajar elfo1 lothlorien amonhen)
(viajar elfo1 amonhen fangorn)
(viajar elfo1 fangorn isengard)
(viajar elfo1 isengard helmsdeep)
(viajar elfo1 helmsdeep tharbad)
(viajar hobbit1 hobbiton bree)
(viajar elfo1 tharbad bree)
(viajar hobbit2 hobbiton bree)
(viajar mago1 rivendell bree)
(formarcomunidad hobbit1 hobbit2 hobbit4 mago1 elfo1 bree)
(viajarcomunidad hobbit1 hobbit2 hobbit4 mago1 elfo1 bree rivendell)
(recogerobjeto hobbit1 rivendell anillo)
(viajarcomunidad hobbit1 hobbit2 hobbit4 mago1 elfo1 rivendell moria)
(materializarchaleco mago1 moria)
(recogerobjeto hobbit1 moria chalecomithril)
(viajarcomunidad hobbit1 hobbit2 hobbit4 mago1 elfo1 moria lothlorien)
(recogerobjeto hobbit1 lothlorien espada)
(viajarcomunidad hobbit1 hobbit2 hobbit4 mago1 elfo1 lothlorien amonhen)
(viajarcomunidad hobbit1 hobbit2 hobbit4 mago1 elfo1 amonhen deadmarshes)
(viajarcomunidad hobbit1 hobbit2 hobbit4 mago1 elfo1 deadmarshes minasmorgul)
(viajarcomunidad hobbit1 hobbit2 hobbit4 mago1 elfo1 minasmorgul orodruin)
(destruiranillo hobbit1 orodruin)
; cost = 23 (unit cost)
