(viajar hobbit2 hobbiton bree)
(extraerrecurso enano1 moria mithril)
(viajar hobbit3 hobbiton bree)
(viajar mago1 rivendell bree)
(formarcomunidad hobbit2 hobbit3 hobbit4 mago1 bree)
(viajarcomunidad hobbit2 hobbit3 hobbit4 mago1 bree rivendell)
(recogerobjeto hobbit2 rivendell anillo)
(viajarcomunidad hobbit2 hobbit3 hobbit4 mago1 rivendell moria)
(materializarchaleco mago1 moria)
(recogerobjeto hobbit2 moria chalecomithril)
(viajarcomunidad hobbit2 hobbit3 hobbit4 mago1 moria lothlorien)
(recogerobjeto hobbit2 lothlorien espada)
(viajarcomunidad hobbit2 hobbit3 hobbit4 mago1 lothlorien amonhen)
(viajarcomunidad hobbit2 hobbit3 hobbit4 mago1 amonhen deadmarshes)
(viajarcomunidad hobbit2 hobbit3 hobbit4 mago1 deadmarshes minasmorgul)
(viajarcomunidad hobbit2 hobbit3 hobbit4 mago1 minasmorgul orodruin)
(destruiranillo hobbit2 orodruin)
; cost = 17 (unit cost)
