(viajar enano1 tharbad bree)
(viajar enano1 bree rivendell)
(viajar hobbit1 lothlorien amonhen)
(viajar hobbit1 amonhen fangorn)
(viajar hobbit1 fangorn isengard)
(viajar hobbit1 isengard helmsdeep)
(viajar hobbit1 helmsdeep tharbad)
(viajar hobbit1 tharbad hobbiton)
(extraerrecurso hobbit1 hobbiton alimento)
(viajar enano1 rivendell moria)
(extraerrecurso enano1 moria mithril)
; cost = 11 (unit cost)
