---
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus_service"
    static_configs:
      - targets: ["prometheus:9090"]
  
  - job_name: "API_Web"
    static_configs:
      - targets: ['host.docker.internal:3000'] # Acceso a API Web
