{
 "title": "jesusMuñozVelascoAPI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tiempo de uso de la CPU (por segundo) [JMV]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta [JMV]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prometheus_http_request_duration_seconds_bucket[1m])) by (le, handler))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria disponible [JMV]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Memoria Total" },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Memoria usada" }
   ]
  }
 ]
}