---
- name: Añadir lista de usuarios añadiéndolos a wheel y dándole llave pública
  hosts: servers
  vars_files:
    - ../vars.yaml
    - ../users.yaml
  become: yes
  tasks:
    - name: Añadir usuarios
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ admin_group }}"
        append: true
        state: present
      loop: "{{ users }}"
    
    - name: Conceder acceso por SSH con llave pública
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('ansible.builtin.file', '../keys/' + item.name + '.pub') }}"
      loop: "{{ users }}"