---
- name: Instalar Nginx y crear página
  hosts: nginx
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Habilitar el puerto HTTP en el firewall
      ansible.posix.firewalld:
        service: http
        permanent: true # para que se guarde al reiniciar
        state: enabled
        immediate: true
      become: true
    
    - name: Instalar Nginx
      ansible.builtin.package:
        name: nginx
        state: present
      become: true
    
    - name: Activar el servicio Nginx 
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      become: true
    
    - name: Crear el archivo index.html
      ansible.builtin.copy:
        dest: "/usr/share/nginx/html/index.html"
        src: "../index.html"
        mode: preserve # conservar los permisos
      become: true