{
 "title": "jesusMuñozVelascoAPI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tiempo de uso de la CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Tiempo de respuesta",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_http_request_duration_seconds_bucket",
     "legendFormat": "t ≤ {{le}}"
    }
   ]
  },
  {
   "title": "Memoria disponible",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Memoria Total" },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Memoria usada" }
   ]
  }
 ]
}