---
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus_service"
    static_configs:
      - targets: ["prometheus:9090"]
  
  - job_name: 'nodejs-api'
    static_configs:
      - targets: ["nodejs:3000"]
